plugin: community.vmware.vmware_vm_inventory
strict: False
hostname: vcsa-1.local.lan
username: administrator@vsphere.local
password: "{{ lookup('hashi_vault', 'secret=secret/vsphere/vcsa:vsphere_password') }}"
validate_certs: False
with_path: yes
properties:
  - 'config.name'
  - 'guest.ipAddress'
  - 'guest.toolsVersionStatus'
  - 'runtime.powerState'
  - 'config.guestId'
  - 'guest.hostName'
  - 'guest.guestFamily'
  - 'guest.ipStack'
hostnames:
  - 'config.name+"."+guest.ipStack.0.dnsConfig.domainName'
  - 'config.name'
filters:
  - runtime.powerState == "poweredOn"
resources:
  - folder:
    - WindowsHL
compose:
  ansible_host: '(config.name+"."+guest.ipStack.0.dnsConfig.domainName)'
  ansible_user: "'ansible@HOMELAB.LOCAL'"
  ansible_password: "{{ lookup('hashi_vault', 'secret=secret/ssh/eingram:ssh_password') }}"
  ansible_connection: "'psrp'"
  ansible_psrp_cert_validation: "'ignore'"
  ansible_psrp_auth: "'kerberos'"
  ansible_psrp_port: "'5985'"
  ansible_psrp_protocol: "'http'"
  ansible_psrp_negotiate_service: "'HTTP'"
  ansible_become_user: "'ansible@HOMELAB.LOCAL'"
  ansible_become_method: "'runas'"
  ansible_become_password: "{{ lookup('hashi_vault', 'secret=secret/ssh/eingram:ssh_password') }}"

  folder: path.split('/')[-1]
# groups:
#   tools: guest.toolsVersionStatus == 'guestToolsCurrent'
keyed_groups:
  - key: folder
    separator: ""
    # prefix: folder
# - key: summary.runtime.powerState
#   separator: ''
