---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--pre'

dependencies:
  ansible_core:
    package_pip: ansible-core==2.15.5
  ansible_runner:
    package_pip: ansible-runner
  python: requirements.txt
  system: bindep.txt
  galaxy: requirements.yml

images:
  base_image:
    name: quay.io/ansible/awx-ee:24.4.0

# additional_build_files:
#     - src: files/ansible.cfg
#       dest: configs

additional_build_steps:
#   prepend_galaxy:
#     - ADD _build/configs/ansible.cfg ~/.ansible.cfg

  prepend_final: |
    RUN whoami
    RUN cat /etc/os-release
  append_final:
    - RUN dnf install -y yum-utils
    - RUN yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    - RUN dnf install -y terraform
    - ADD vault.ca /etc/vault.ca
    - RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/arm64/kubectl"
    - RUN mv ./kubectl /usr/local/bin
    - RUN curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
    - RUN chmod +x /usr/local/bin/kubectl
    - RUN chmod +x /usr/local/bin/helm
    - ENV TF_CLI_ARGS_apply=-parallelism=1 \
          TF_CLI_ARGS_destroy=-parallelism=1 \
          TF_LOG=INFO

