---
version: 1
build_arg_defaults:
  EE_BASE_IMAGE: 'quay.io/ansible/awx-ee:latest'
dependencies:
  system: bindep.txt
  python: requirements.txt
additional_build_steps:
  append:
    - RUN alternatives --set python /usr/bin/python3
    # - COPY --from=quay.io/ansible/receptor:devel /usr/bin/receptor /usr/bin/receptor
    # - RUN mkdir -p /var/run/receptor
    - RUN dnf install -y yum-utils
    - RUN yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    - RUN dnf install -y terraform
    - ADD vault.ca /etc/vault.ca
    - ENV TF_CLI_ARGS_apply=-parallelism=1 \
          TF_CLI_ARGS_destroy=-parallelism=1 \
          TF_LOG=INFO
    - USER 1000
    # - RUN git lfs install --system