---
version: 1
build_arg_defaults:
  EE_BASE_IMAGE: 'quay.io/ansible/ansible-runner:latest'
dependencies:
  galaxy: requirements.yml
  system: bindep.txt
  python: requirements.txt
additional_build_steps:
  append:
    - RUN alternatives --set python /usr/bin/python3
    - COPY --from=quay.io/ansible/receptor:devel /usr/bin/receptor /usr/bin/receptor
    - RUN mkdir -p /var/run/receptor
    - RUN dnf update
    - RUN dnf install -y yum-utils
    - RUN yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    - RUN dnf install -y terraform
    - RUN dnf install -y mysql
    - RUN export TF_CLI_ARGS_apply='-parallelism=1'
    - RUN export TF_CLI_ARGS_destroy='-parallelism=1'
    - ADD vault.ca /etc/vault.ca
    - RUN export VAULT_ADDR=https://vault.local.lan
    - RUN export VAULT_CACERT=/etc/vault.ca
    - RUN export VAULT_TOKEN=hvs.ac1ejE5h5CJIABCcv9nFWvkz
    - USER 1000
    - RUN git lfs install
